USE DATABASE DB1;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS SUPPLIERS (
  supplier_id INTEGER NOT NULL,
  farm_name STRING NOT NULL,
  region STRING NOT NULL,
  CONSTRAINT PK_SUPPLIERS PRIMARY KEY (supplier_id),
  CONSTRAINT UQ_SUPPLIERS_FARM_REGION UNIQUE (farm_name, region)
);

CREATE TABLE IF NOT EXISTS ORDERSS (
  order_id INTEGER NOT NULL,
  supplier_id INTEGER NOT NULL,
  order_date DATE NOT NULL,
  total_price NUMBER(12,2) NOT NULL,
  CONSTRAINT PK_ORDERSS PRIMARY KEY (order_id),
  CONSTRAINT FK_ORDERSS_SUPPLIERS FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS(supplier_id)
);

CREATE TABLE IF NOT EXISTS SALES_TARGETS (
  region STRING NOT NULL,
  quarter STRING NOT NULL,
  target_amount NUMBER(12,2) NOT NULL,
  CONSTRAINT PK_SALES_TARGETS PRIMARY KEY (region, quarter)
);

CREATE TABLE IF NOT EXISTS CERTIFICATIONS (
  certification_id INTEGER AUTOINCREMENT,
  supplier_id INTEGER NOT NULL,
  cert_name STRING NOT NULL,
  issued_date DATE NOT NULL,
  expiry_date DATE,
  CONSTRAINT PK_CERTIFICATIONS PRIMARY KEY (certification_id),
  CONSTRAINT FK_CERTIFICATIONS_SUPPLIERS FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS(supplier_id),
  CONSTRAINT UQ_CERTIFICATIONS_SUPPLIER_CERT UNIQUE (supplier_id, cert_name)
);

CREATE TABLE IF NOT EXISTS HARVEST_LOG (
  harvest_id INTEGER AUTOINCREMENT,
  supplier_id INTEGER NOT NULL,
  harvest_date DATE NOT NULL,
  crop STRING NOT NULL,
  quantity_kg NUMBER(12,2) NOT NULL,
  grade STRING NOT NULL,
  notes STRING,
  CONSTRAINT PK_HARVEST_LOG PRIMARY KEY (harvest_id),
  CONSTRAINT FK_HARVEST_LOG_SUPPLIERS FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS(supplier_id),
  CONSTRAINT UQ_HARVEST_LOG UNIQUE (supplier_id, harvest_date, crop)
);
